### ISSUE TITLE
为什么style="box-shadow: transparent 0px 0px;"会影响getClientRects的值?

### ISSUE THREAD

**Issue by HHHui** [Justineo/vue-clamp#1]
这个组件真的很有用, 但是我的项目是Angular的, 所以我学习了一下源码的实现. 但是发现自己的`getClientRects`返回值不对, 对比了好久发现是`style="box-shadow: transparent 0px 0px;"`的作用, 但是不知道这底层的原因是什么? 这两者之间有什么影响?
希望大神指教.

**Comment by Justineo** [comment]
这可以算是 Chromium 的一个 bug，而且他们确认 won’t fix 了。至于为什么加了特定的样式就好了……我也不知道原理，只是很久以前试过试出来的。我记得设置 `opacity` 也是可以的。

**Comment by HHHui** [comment]
多谢指教~
