### ISSUE TITLE
Implement v-clamp with v-html

### ISSUE THREAD

**Issue by ChunAllen** [Justineo/vue-clamp#14]
I'm currently using Vuetify and Vue-Clamp 
The `body` contains html elements such as `span`, `<b></b>`, `<p></p> etc...`

I tried 
```
<div class="caption mb-3">
    <v-clamp autoresize :max-lines="10" v-html="body"></v-clamp>
</div>
```
and
```
<v-clamp autoresize :max-lines="10">
   <div class="caption mb-3" v-html="body"></body>
</v-clamp>
```
But both approach doesn't work

**Comment by Justineo** [comment]
Duplicate of #13

**Comment by brmdbr** [comment]
@ChunAllen Have you found a solution for this? Running into the same problem.

**Comment by drayanaindra** [comment]
Hi, i also have same issue. Any suggestion to solve this issue?
