### ISSUE TITLE
webpack  打包后  里面还有es6的语法

### ISSUE THREAD

**Issue by suichukewan** [Justineo/vue-clamp#15]

**Comment by Justineo** [comment]
请按阅读[文档](https://justineo.github.io/vue-clamp/demo/?lang=zh#usage)。

**Comment by suichukewan** [comment]
![image](https://user-images.githubusercontent.com/19454577/63248260-7e85e600-c299-11e9-9a4a-ea82b45d9e25.png)
按照这个配置过了，不知道为啥，  只好用这种 **import VClamp from 'vue-clamp/dist/vue-clamp'**方式导入了。

**Comment by Justineo** [comment]
Windows 下的话注意 `/` 分隔符应该重写为 `\\`

**Comment by suichukewan** [comment]
> Windows 下的话注意 `/` 分隔符应该重写为 `\\`

![image](https://user-images.githubusercontent.com/19454577/63570075-789c4780-c5ae-11e9-870a-b1e8cb502db1.png)
是这个吗？ 可是上面的`resolve('node_modules/webpack-dev-server/client'),` 也是这样写的呢

**Comment by suichukewan** [comment]
老哥 ，能说具体点吗
