### ISSUE TITLE
Vue-Clamp and slots

### ISSUE THREAD

**Issue by mituller** [Justineo/vue-clamp#16]
I am trying to get this working with a slot, but can't seem to get it working. When I load the page, the content is missing, but there are no errors. I didn't see examples, so I tried to follow what you had in the App.vue in the repo. Here is what I have.

Communications.vue
I loop through and call the instances of communications
```
<article v-for="communication in communications">
   <CommunicationInstance>
       <img slot="image":src="require('../assets/images/' + communication.image)" />
       <i slot="date">{{ communication.date }}</i>
       <div slot="content">{{ communication.content }}</div>
   </CommunicationInstance>
</article>
```
And then in the CommunicationsInstance.vue I have for the part that I was vue-clamp to be used:

```
            <div class="communication-instance-content">
                <v-clamp class="communication-instance-content" :max-lines="lines" auto-resize>
                    <slot name="content"></slot>
                </v-clamp>
            </div>
```

Then within the script tag I have 

```
import VClamp from 'vue-clamp'
export default {
    data() {
        return {
            lines: 3,
            expanded: false
        }
    },
    components: {
        VClamp
    }
    
}
```

And in the vue.config.js file I have:

```
module.exports = {
  transpileDependencies: ['vue-clamp', 'resize-detector']
};
```

What am I doing wrong here?

**Comment by mituller** [comment]
I was calling from the parent, when I should have called from the child. Works now.

**Comment by kbarrette** [comment]
@mituller I'm looking at a very similar situation - can you clarify what you changed to make your example work?
