### ISSUE TITLE
Access in "after" slot to isClamped

### ISSUE THREAD

**Issue by inforemberto** [Justineo/vue-clamp#18]
I write some text after the text only if is clamped.

You can add some attribute to know if the text was processed( for computed isClamped) or not?

Example:

Hello -> never clamped
Hello aga... -> clamped

**Comment by Justineo** [comment]
As documented, it's already available as `clamped` via slot props: https://codesandbox.io/s/vue-template-253hu

**Comment by inforemberto** [comment]
Thanks,
I was looking for something like this

`<button
        v-if="(expanded || clamped)"
        slot="after"
        slot-scope="{ toggle, expanded, clamped, candidate }"
        class="toggle btn btn-sm"
        @click="toggle"
      >`

To not show the button if I did not apply any transformation to the original text
The demo code was very helpful
