### ISSUE TITLE
Autoresize doesn't work as intended in a flex container

### ISSUE THREAD

**Issue by benjaminwaterlot** [Justineo/vue-clamp#29]
When put in a flex container, everything seems to work correctly but one thing:

The content clamps correctly when the size is being reduced, but **not the other way around**: it stays clamped when the size of the flex container is increasing, even if there is now enough space for the content to display.

### To reproduce:

Here is a simple example, just try to resize your screen downwards, then upwards:

```html
    <div style="display: flex;">
      <v-clamp
        autoresize
        :max-lines="1"
      >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
      </v-clamp>
    </div>
```

Tested in Chrome 79.0.3945.130 and Safari 13.0.4.

**Comment by Justineo** [comment]
You need to wrap it in an element with `display: block`. Otherwise actual line count cannot be detected reliably.
