### ISSUE TITLE
[BUG][兼容性] 在 direction == 'rtl' 的情况下，获取行数错误

### ISSUE THREAD

**Issue by zyjwsg** [Justineo/vue-clamp#36]
**异常浏览器：**
Firefox

**现象：**
切换为从右至左布局后，触发组件更新，将显示错误的折叠文本

**正常样式：**
![image](https://user-images.githubusercontent.com/7666606/87379823-b5f13580-c5c3-11ea-9d94-f0969d49ff29.png)

**异常样式：**
![image](https://user-images.githubusercontent.com/7666606/87380351-e2f21800-c5c4-11ea-91d6-c15a7699d9f0.png)

**复现步奏：**
1. 设置父容器样式 direction: "rtl";
2. 触发 v-clamp 更新（v-if 重新渲染；若监听size变化，可调整窗口大小；等）

**问题分析：**
查看源码发现判断 [isOverflow](https://github.com/Justineo/vue-clamp/blob/master/src/components/Clamp.js#L133) 方法中使用了dom 元素的 [_getClientRects()_](https://github.com/Justineo/vue-clamp/blob/master/src/components/Clamp.js#L125) 方法判断行数，该方法存在**兼容性问题**

如图 Firefox：
![image](https://user-images.githubusercontent.com/7666606/87381250-d53d9200-c5c6-11ea-8db0-1dab18cd4cd6.png)
![image](https://user-images.githubusercontent.com/7666606/87381264-da9adc80-c5c6-11ea-91b6-4c1373ca085a.png)

对比 Chrome：
![image](https://user-images.githubusercontent.com/7666606/87381443-5563f780-c5c7-11ea-8b7d-cb75799cab87.png)

**Comment by zyjwsg** [comment]
@Justineo 

据观察，
1. 反向后文本前后可能会出现多余的宽度为 0 的 DOMRect，需按宽度过滤
2. 结尾的标点符号（比如…）会产生和正常文本 top/bottom 一致的多余的 DOMRect，可按 top/bottom 值过滤
如图：
![image](https://user-images.githubusercontent.com/7666606/87415018-25d0e180-c5ff-11ea-8bd3-d34bae194203.png)

故按如下修改 getLines，简单测试下能够正常使用
```
getLines () {
  return new Set([...this.$refs.content.getClientRects()].filter(item => item.width > 0).map(rect => Math.round(rect.top))).size;
},
```
😄

**Comment by Justineo** [comment]
我感觉是不是不需要判断宽度为 0 了，直接看有多少不同的 `top` & `bottom` 就行了？

**Comment by zyjwsg** [comment]
> 我感觉是不是不需要判断宽度为 0 了，直接看有多少不同的 `top` & `bottom` 就行了？

👍 
好像是可以只看 top、bottom，目前测下来没发现问题

测试结果：
edge、ie11、chrome 正常，
firefox getClientRects() 返回的宽度为 0  元素总是 [0] 元素，同时 top bottom 和真实文本第一行的 DOMRect 一致

单看实验现象，认为不同的 top bottom 的数量就是行数应该是可行的

**Comment by Justineo** [comment]
Fixed in 0876b1e2093886db809808f9245a3804d9900db4.
