### ISSUE TITLE
Doesn't work in nuxtjs

### ISSUE THREAD

**Issue by ysq352358871** [Justineo/vue-clamp#40]
```
[Vue warn]: Unknown custom element: <vue-clamp> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Card> at components/page/card.vue
       <Pages/Lang/index.vue> at pages/_lang/index.vue
         <Nuxt>
           <VMain>
             <VApp>
               <Layouts/default.vue> at layouts/default.vue
                 <Root>
```

**Comment by Justineo** [comment]
Apparently you didn't register the component correctly in you code.

**Comment by ysq352358871** [comment]
**In nuxt.config.js:**
build: {
    transpile: ['vue-clamp', 'resize-detector'],
    analyze:true,
    extractCSS: true
  }

**In page:**

import VClamp from 'vue-clamp'
  export default {
    name: "card",
    comments:{
      VClamp
    },
    data: () => ({
      show: false,
      html:`<p>I'm a thing.</p> But, like most politicians, he promised more than he could deliver. You won't have time for sleeping, soldier, not with all the bed making you'll be doing. Then we'll go with that data file! Hey, you add a one and two zeros to that or we walk! You're going to do his laundry? I've got to find a way to escape.`,
      text:" But, like most politicians, he promised more than he could deliver. You won't have time for sleeping, soldier, not with all the bed making you'll be doing. Then we'll go with that data file! Hey, you add a one and two zeros to that or we walk! You're going to do his laundry? I've got to find a way to escape."
    })
  }

**Use as follows:**
```
<div class="pa-0 card-overview-text">
        <v-clamp autoresize :max-lines="3">{{ text }}</v-clamp>
      </div>
```

**But i get the same error**
[Vue warn]: Unknown custom element: <v-clamp> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in
