### ISSUE TITLE
希望可以以任何形式把“是否省略”的状态值给传出来

### ISSUE THREAD

**Issue by Array-Huang** [Justineo/vue-clamp#5]
有了这个“是否省略”的状态值，可以实现这样的需求：
- 已被省略的文本可以加上title属性显示完整内容，未被省略的文本则不需要加title属性
- 已被忽略的文本末尾可以加上按钮来触发展开完整文本内容，而未被忽略的文本末尾就不需要有这个按钮

**Comment by Array-Huang** [comment]
看漏了，原来slots里有这个状态值，这样我上面说的第二条就可以做了，只是第一条还做不了

**Comment by Justineo** [comment]
可以暴露一个 `clampchange` 事件出来？

**Comment by Array-Huang** [comment]
> 可以暴露一个 `clampchange` 事件出来？

我觉得可以

**Comment by Array-Huang** [comment]
我又想了一下，在default的slot里传出来可能更好，因为如果是循环渲染的场景，用clampchange事件把值传出来后我还要想怎么保存这个值

**Comment by Justineo** [comment]
现在 `default` slot 只能传纯文本，你用不了。

**Comment by Array-Huang** [comment]
嗯？是什么原因default slot不能提供slot-scope呢？

**Comment by Justineo** [comment]
提供了你也用不了啊。

**Comment by Array-Huang** [comment]
为嘛用不到啊，官方文档：
```
<slot-example>
  <template slot="default" slot-scope="slotProps">
    {{ slotProps.msg }}
  </template>
</slot-example>

```

**Comment by Justineo** [comment]
`vue-clamp` 的 default slot 目前只支持纯文本。你在 default slot 参数里拿到了状态也没有地方可以用。

**Comment by Array-Huang** [comment]
哦，明白了

**Comment by smelyakov** [comment]
@Array-Huang 
this is exactly why I'd like to have something like this https://github.com/Justineo/vue-clamp/pull/30

**Comment by Justineo** [comment]
Implemented in #30.
