### ISSUE TITLE
切换

### ISSUE THREAD

**Issue by JackYangFM** [Justineo/vue-clamp#6]
您好，超出规定行数，展开收起超出文字，我用slot插槽没起作用，想请问一下该怎么解决一下啊

**Comment by Justineo** [comment]
你的提问没有任何信息，无法提供帮助。请提供最小可复现的场景。

**Comment by Justineo** [comment]
请提供一个**可运行**的最小复现后重新提交 issue，谢谢。

**Comment by JackYangFM** [comment]
<v-clamp autoresize :max-lines="5" :expanded="false" class="comment-txt">
                      {{faqDetail.accept_answer_lst.content}}
                      <span
                        slot="after"
                        slot-scope="{ toggle }"
                      >{{exchangeButton ? '展开' : '收起'}}</span>
                    </v-clamp>
slot-scope不知道是不是这么用，想请教一下
