### ISSUE TITLE
Why transpile?

### ISSUE THREAD

**Issue by franciscolourenco** [Justineo/vue-clamp#9]
Why isn't the package already in ES5?

**Comment by Justineo** [comment]
To reduce transpile overhead in production. https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

**Comment by Justineo** [comment]
And F.Y.I. if you are not using some module bundler which recognizes ESM packages via the `module` field of `package.json` like webpack or Rollup, there is a transpiled version at `dist/vue-clamp.js`. (Or you can manually require that UMD module.)

**Comment by franciscolourenco** [comment]
This should be implemented as an optional opt-in.

**Comment by Justineo** [comment]
Well, I actually intentionally chose to publish the package in this way. It's a trade-off and I personally would put performance and end-user experience over developer experience. Package consumers would have to choose either:

1. Clean source code (`import VueClamp from 'vue-clamp'`) and a bit work of configuration, to gain smallest bundle.
2. or annoying import statement (`import VueClamp from 'vue-clamp/dist/vue-clamp'`), with potentially unnecessary/redundant code with lead to larger bundle size.
